import React from 'react';
import { X, Sparkles, Download, Copy, Check, ShieldCheck, Award, Layers } from 'lucide-react';
import { ChoiceFillingItem } from '../types';

interface AIChoiceFillerModalProps {
  isOpen: boolean;
  onClose: () => void;
  choices: ChoiceFillingItem[];
  percentile: number;
  air: number;
  category: string;
}

export const AIChoiceFillerModal: React.FC<AIChoiceFillerModalProps> = ({
  isOpen,
  onClose,
  choices,
  percentile,
  air,
  category,
}) => {
  const [copied, setCopied] = React.useState(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    const text = choices
      .map(
        (c) =>
          `Pref #${c.preference_number}: ${c.institute_name} | ${c.branch} (${c.type}) [Cutoff Rank: ${c.closing_rank}] - ${c.chance_level} Chance`
      )
      .join('\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const mdContent = `# JoSAA / CSAB AI Choice Filling Preference Order
**JEE Main Percentile:** ${percentile}% | **Estimated AIR:** ${air.toLocaleString()} | **Category:** ${category}

| Pref # | Institute Name | Preferred Branch | Type | Closing Cutoff | Chance Level | Counselling Strategy |
| :---: | :--- | :--- | :---: | :---: | :---: | :--- |
${choices
  .map(
    (c) =>
      `| **${c.preference_number}** | ${c.institute_name} | ${c.branch} | \`${c.type}\` | ${c.closing_rank.toLocaleString()} | **${c.chance_level}** | ${c.strategy_note} |`
  )
  .join('\n')}

---
*Generated by UniGuide AI Choice Filler Assistant*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `JoSAA_Choice_Filling_Preference_List.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="p-6 bg-gradient-to-r from-brand-700 via-indigo-700 to-purple-800 text-white flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-white/10 rounded-xl backdrop-blur-md border border-white/20">
              <Sparkles className="w-6 h-6 text-amber-300 animate-pulse" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-extrabold tracking-tight">JoSAA AI Choice Filler Assistant</h2>
                <span className="text-[10px] bg-amber-400 text-slate-950 font-bold px-2 py-0.5 rounded-full uppercase tracking-wider">
                  AI Optimized
                </span>
              </div>
              <p className="text-xs text-brand-100 font-medium">
                AIR #{air.toLocaleString()} • {percentile}%ile • Category: {category}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-white/80 hover:text-white bg-white/10 hover:bg-white/20 rounded-xl transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Info Banner */}
        <div className="px-6 py-3 bg-brand-50 border-b border-brand-100 flex items-center justify-between text-xs text-brand-800">
          <div className="flex items-center gap-2 font-medium">
            <ShieldCheck className="w-4 h-4 text-brand-600" />
            <span>Structured strategy: Dream tier at top $\rightarrow$ Target colleges in middle $\rightarrow$ Safe backup options at bottom.</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-slate-50 border border-slate-200 rounded-lg text-slate-700 font-bold text-xs shadow-sm transition"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-brand-600" />}
              <span>{copied ? 'Copied!' : 'Copy List'}</span>
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 px-3.5 py-1.5 bg-brand-600 hover:bg-brand-700 text-white rounded-lg font-bold text-xs shadow-md transition"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export .md</span>
            </button>
          </div>
        </div>

        {/* Choice List Table */}
        <div className="p-6 overflow-y-auto flex-1 space-y-3">
          {choices.map((choice) => {
            const chanceBadgeColor =
              choice.chance_level === 'High'
                ? 'bg-emerald-100 text-emerald-800 border-emerald-300'
                : choice.chance_level === 'Moderate'
                ? 'bg-amber-100 text-amber-800 border-amber-300'
                : 'bg-rose-100 text-rose-800 border-rose-300';

            return (
              <div
                key={choice.preference_number}
                className="p-4 bg-white hover:bg-slate-50 border border-slate-200 rounded-xl shadow-sm transition flex flex-col md:flex-row md:items-center justify-between gap-4"
              >
                <div className="flex items-start gap-3">
                  <div className="w-8 h-8 rounded-xl bg-slate-900 text-white flex items-center justify-center font-extrabold text-sm shadow-md shrink-0">
                    #{choice.preference_number}
                  </div>
                  <div>
                    <div className="flex items-center gap-2 flex-wrap">
                      <h4 className="font-bold text-slate-900 text-sm">{choice.institute_name}</h4>
                      <span className="text-[10px] bg-slate-100 text-slate-700 font-bold px-2 py-0.5 rounded border border-slate-200">
                        {choice.type}
                      </span>
                    </div>
                    <p className="text-xs font-semibold text-brand-700 mt-0.5">{choice.branch}</p>
                    <p className="text-[11px] text-slate-500 mt-1 italic">{choice.strategy_note}</p>
                  </div>
                </div>

                <div className="flex items-center gap-4 border-t md:border-t-0 pt-2 md:pt-0 shrink-0">
                  <div className="text-right">
                    <span className="text-[10px] uppercase text-slate-400 font-bold tracking-wider block">JoSAA Cutoff</span>
                    <span className="font-bold text-slate-800 text-xs">AIR #{choice.closing_rank.toLocaleString()}</span>
                  </div>
                  <span className={`px-2.5 py-1 rounded-full text-xs font-bold border ${chanceBadgeColor}`}>
                    {choice.chance_level} Chance
                  </span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-50 border-t border-slate-200 flex justify-between items-center text-xs text-slate-500 font-medium">
          <div className="flex items-center gap-1.5">
            <Layers className="w-4 h-4 text-brand-600" />
            <span>JoSAA Round 1-6 & CSAB Special Round Cutoff Matrix</span>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl font-bold transition shadow-sm"
          >
            Close Window
          </button>
        </div>
      </div>
    </div>
  );
};
